server:
  port: 8080
spring:
  #security:
    #user:
     # name: usuario1
      #password: P@ssw0rd+*2022
  application:
    name: "cuenta-bancaria-project"
  devtools:
    add-properties: false
  profiles:
    include: null
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:mysql://localhost/banco_cuentas_cliente"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.MySQL57Dialect"
    hibernate:
      ddl-auto: "create-drop"
    properties:
      hibernate:
        format-sql: true
      show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

logging.level.org.hibernate.SQL: debug
